# Generated by Django 3.0.6 on 2020-06-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
