# Generated by Django 3.0.6 on 2020-05-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(choices=[(1, 'Electrician'), (2, 'Plumber'), (3, 'Painter'), (4, 'Beautician'), (5, 'Cleaner')], to='people.Role'),
        ),
    ]
