# Generated by Django 3.0.6 on 2020-06-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_remove_customer_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
    ]
